In [278]:
import pandas as pd

In [279]:
rewards_df = pd.read_csv('RewardsData.csv')

In [280]:
rewards_df.head(20)

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,ClassOf2025
1,2,NaN,Los Angeles,Colorado,90210,320,320,0,8/19/2020 11:15,4/13/2022 14:28,ClassOf2025|apple
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55,GraduateStudent|admin
6,7,9/22/1995,NaN,NaN,NaN,570,570,0,8/21/2020 10:23,4/27/2022 16:27,ClassOf2025
7,8,NaN,NaN,NaN,NaN,2410,2410,0,8/22/2020 13:53,3/31/2022 1:56,ClassOf2022|21DZ
8,9,NaN,NaN,NaN,NaN,2895,3195,300,8/22/2020 14:03,10/10/2021 16:05,Student|Senior|DriveInNCSU|ClassificationPts|1...
9,10,7/20/1999,Winston Salem,NC,27106,8465,8515,50,8/22/2020 14:42,4/9/2022 14:10,GraduateStudent
10,11,7/22/2000,NaN,NaN,NaN,22210,22210,0,8/22/2020 15:59,6/21/2022 19:32,ClassOf2022
11,12,NaN,NaN,NaN,NaN,1355,4355,3000,8/22/2020 17:37,5/18/2021 20:57,Student|Senior|DriveInNCSU|ClassificationPts|1...
12,13,NaN,NaN,NaN,NaN,3290,3290,0,8/22/2020 18:20,4/10/2022 23:04,Student|Senior|ClassificationPts|CampbellGroup...
13,14,11/1/2000,Winston-Salem,NC,27106,10965,17165,6200,8/22/2020 20:02,5/11/2022 15:16,ClassOf2023|MBBvsDuke
14,15,6/27/2000,Thomasville,NC,27360,5750,5750,0,8/23/2020 9:26,4/11/2022 16:27,ClassOf2022
15,16,4/24/1999,NaN,NaN,NaN,4310,4610,300,8/23/2020 23:43,8/27/2021 13:01,Student|Senior|ClassificationPts|BSBvNDGame1|B...
16,17,NaN,NaN,NaN,NaN,890,890,0,8/24/2020 11:30,1/23/2022 23:28,ClassOf2022
17,18,7/5/1998,NaN,NaN,NaN,550,550,0,8/24/2020 14:48,10/26/2020 10:01,NOBSBvsNDGame3|NOBSBvsNDGame3A
18,19,NaN,Goldsboro,North Carolina,27534,3425,3425,0,8/24/2020 15:35,6/30/2022 21:19,ClassOf2023|21EPI|MBBvsDuke
19,20,NaN,NaN,NaN,NaN,800,800,0,8/24/2020 18:23,NaN,Student|19RetroactivePoints|NOBSBvsNDGame3|NOB...

## Data Wrangling Stages

There are several stages in data wrangling. The first phase is:

## 1. Handling Missing Values

We can handle missing values using two common methods:

- **Dropping incomplete records**  
  Removing rows or columns that contain missing values.

- **Filling missing values**  
  Replacing missing values with an appropriate substitute (e.g., mean, median, or a constant value).

Before deciding how to handle missing values, it is important to assess the data. This helps in choosing the most appropriate method for treatment.

In [281]:
missing_values_count = rewards_df.isna().sum()
missing_values_count

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen               221
Tags                      0
dtype: int64

In [282]:
percentage_missing_values = missing_values_count/ len(rewards_df)  * 100
percentage_missing_values

User ID                 0.000000
Birthdate              83.838941
City                   95.449531
State                  95.449531
Zip                    95.449531
Available Points        0.000000
Total Points Earned     0.000000
Points Spent            0.000000
Joined On               0.000000
Last Seen               3.047435
Tags                    0.000000
dtype: float64

From the assessment, the columns **birthday**, **city**, **state**, and **zip** have a high percentage of missing values.  

Due to the large amount of missing data, these columns may not be reliable and could be considered for removal or handled with caution.

On the other hand, the **lastSeen** column has a relatively low percentage of missing values.  
Therefore, instead of dropping it, we will try to fill in the missing values using appropriate techniques.

In [283]:
rewards_df['Last Seen']

0       12/16/2021 17:42
1        4/13/2022 14:28
2        4/21/2021 10:54
3        6/30/2022 22:22
4       12/30/2020 10:57
              ...
7247     6/30/2022 12:04
7248     6/28/2022 22:43
7249     6/30/2022 12:48
7250     6/30/2022 20:39
7251       7/1/2022 2:42
Name: Last Seen, Length: 7252, dtype: str

In [284]:
#Convert to datetime as it is string
rewards_df['Last Seen'] = pd.to_datetime(rewards_df['Last Seen'])

In [285]:
rewards_df['Last Seen']

0      2021-12-16 17:42:00
1      2022-04-13 14:28:00
2      2021-04-21 10:54:00
3      2022-06-30 22:22:00
4      2020-12-30 10:57:00
               ...
7247   2022-06-30 12:04:00
7248   2022-06-28 22:43:00
7249   2022-06-30 12:48:00
7250   2022-06-30 20:39:00
7251   2022-07-01 02:42:00
Name: Last Seen, Length: 7252, dtype: datetime64[us]

In [286]:
rewards_df['Last Seen'].max()

Timestamp('2022-07-01 08:36:00')

In [287]:
rewards_df['Last Seen'].min()

Timestamp('2020-10-12 14:38:00')

Since we know the minimum and maximum values of the `lastSeen` column, we can use this information to approximate the missing entries.To handle the missing values, we will fill them using the **minimum value** of the `lastSeen` column. This approach assumes that missing entries correspond to the earliest observed activity.

In [288]:
rewards_df['Last Seen'] = rewards_df['Last Seen'].fillna(rewards_df['Last Seen'].min())

In [289]:
missing_values_count = rewards_df.isna().sum()
missing_values_count

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen                 0
Tags                      0
dtype: int64

Since the columns **birthday**, **city**, **state**, and **zip** contain a high percentage of missing values, we will drop them from the dataset.

After removing these columns, we will evaluate whether the remaining data is sufficient to perform meaningful analysis.

In [290]:
rewards_df_sample = rewards_df.dropna()
rewards_df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,ClassOf2025
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,GraduateStudent|admin
...,...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00,Student|ClassOf2026
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00,Student|ClassOf2023
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00,Student|GraduateStudent
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00,Student|GraduateStudent
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00,Student|ClassOf2026

In [291]:
missing_values_count = rewards_df_sample.isna().sum()
missing_values_count

User ID                0
Birthdate              0
City                   0
State                  0
Zip                    0
Available Points       0
Total Points Earned    0
Points Spent           0
Joined On              0
Last Seen              0
Tags                   0
dtype: int64

In [292]:
#Lets drop tags as it isnt useful
rewards_df_sample = rewards_df_sample.drop(columns='Tags')
rewards_df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00
...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,2022-06-30 08:43:00
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,2022-06-26 16:39:00
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,2022-06-29 23:40:00
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,2022-06-24 16:06:00
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,2022-07-01 08:36:00

## Stage 2: Handling Messy and Inconsistent Data

Now we move to the second stage of data wrangling: handling messy or inconsistent data.

This stage involves:

- Correcting inconsistent formatting (e.g., date formats, text casing)  
- Standardizing values (e.g., "NY", "New York", "new york" → "New York")  
- Fixing data entry errors or typos  
- Ensuring uniform data types across columns  

Cleaning inconsistent data helps improve data quality and ensures more accurate analysis.

In [293]:
city_unique_values = rewards_df_sample['City'].unique()
city_unique_values = sorted(city_unique_values)
city_unique_values

['Atlanta',
 'Aurora ',
 'Austin',
 'Bakersfield',
 'Belmont ',
 'Bethesda ',
 'Bourne',
 'Chapel Hill',
 'Charlotte',
 'Charlotte ',
 'Clemmons',
 'Cleveland',
 'Clovis',
 'Dallas',
 'Delhi',
 'Delran',
 'Downers Grove',
 'Durham',
 'Duxbury',
 'Edina',
 'Fort Myers ',
 'G',
 'Gainesville',
 'Greensboro',
 'Guaynabo',
 'Huntersville',
 'Indian Trail',
 'Jacksonville ',
 'Jamesville',
 'Larchmont',
 'Libertyville',
 'Lincoln University',
 'Littleton',
 'Lmao',
 'Locust',
 'Louisville',
 'Lutherville',
 'Malvern',
 'Manhattan beach ',
 'Marblehead',
 'Memphis',
 'Merida',
 'Milwaukee',
 'Minneapolis ',
 'Mooresville',
 'Morganton',
 'Mt. Pleasant ',
 'Nashville',
 'Northport',
 'Oakwood',
 'Orleans ',
 'Ormond Beach',
 'Palm Beach Gardens',
 'Palmetto Bay',
 'Perry',
 'Pittsburgh',
 'Rex',
 'Rocky hill',
 'Rome',
 'San Marcos',
 'Sharon',
 'Smithtown',
 'Summit',
 'Supply',
 'Terrace Park',
 'Thomasville',
 'Valrico ',
 'Walkertown',
 'Waukegan',
 'Waxhaw',
 'West Chester',
 'Weston',
 'Westport',
 'Whitesboro',
 'Winston Salem',
 'Winston Salem ',
 'Winston salem',
 'Winston salem ',
 'Winston-Salem',
 'Winston-Salem ',
 'Winston-Salem, NC',
 'Winston-salem',
 'Wyckoff',
 'dover',
 'winston salem ']

Here, we observe that the same city names are stored in different formats. This inconsistency can lead to incorrect analysis and grouping.

To address this, we need to standardize the city name.

In [294]:
rewards_df_sample['City'] = rewards_df_sample['City'].replace(to_replace = [ 'Winston Salem',
 'Winston Salem ',
 'Winston salem',
 'Winston salem ',
 'Winston-Salem',
 'Winston-Salem ',
 'Winston-Salem, NC',
 'Winston-salem',
 'Wyckoff',
 'dover',
 'winston salem '], value="Winston-Salem")

In [295]:
rewards_df_sample['City'] = rewards_df_sample['City'].str.strip()

In [296]:
rewards_df_sample['City'] = rewards_df_sample['City'].str.title()

In [297]:
city_unique_values = rewards_df_sample['City'].unique()
city_unique_values = sorted(city_unique_values)
city_unique_values

['Atlanta',
 'Aurora',
 'Austin',
 'Bakersfield',
 'Belmont',
 'Bethesda',
 'Bourne',
 'Chapel Hill',
 'Charlotte',
 'Clemmons',
 'Cleveland',
 'Clovis',
 'Dallas',
 'Delhi',
 'Delran',
 'Downers Grove',
 'Durham',
 'Duxbury',
 'Edina',
 'Fort Myers',
 'G',
 'Gainesville',
 'Greensboro',
 'Guaynabo',
 'Huntersville',
 'Indian Trail',
 'Jacksonville',
 'Jamesville',
 'Larchmont',
 'Libertyville',
 'Lincoln University',
 'Littleton',
 'Lmao',
 'Locust',
 'Louisville',
 'Lutherville',
 'Malvern',
 'Manhattan Beach',
 'Marblehead',
 'Memphis',
 'Merida',
 'Milwaukee',
 'Minneapolis',
 'Mooresville',
 'Morganton',
 'Mt. Pleasant',
 'Nashville',
 'Northport',
 'Oakwood',
 'Orleans',
 'Ormond Beach',
 'Palm Beach Gardens',
 'Palmetto Bay',
 'Perry',
 'Pittsburgh',
 'Rex',
 'Rocky Hill',
 'Rome',
 'San Marcos',
 'Sharon',
 'Smithtown',
 'Summit',
 'Supply',
 'Terrace Park',
 'Thomasville',
 'Valrico',
 'Walkertown',
 'Waukegan',
 'Waxhaw',
 'West Chester',
 'Weston',
 'Westport',
 'Whitesboro',
 'Winston-Salem']

Lets do the same for state and zip

In [298]:
state_unique_values = rewards_df_sample['State'].unique()
state_unique_values = sorted(state_unique_values)
state_unique_values

['AL',
 'CT',
 'California',
 'Colorado',
 'Connecticut',
 'District of Columbia',
 'FL',
 'Florida',
 'GA',
 'Georgia',
 'Illinois',
 'Kentucky',
 'MA',
 'MD',
 'MN',
 'Maryland',
 'Massachusetts',
 'NC',
 'NJ',
 'NY',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'OH',
 'Ohio',
 'PA',
 'Pennsylvania',
 'Puerto Rico',
 'SC',
 'TN',
 'TX',
 'Tennessee',
 'Texas',
 'WI']

In [299]:
state_abbrev = {
    # States
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",

    # Federal district
    "District of Columbia": "DC",

    # Territories
    "Puerto Rico": "PR",
    "Guam": "GU",
    "American Samoa": "AS",
    "Northern Mariana Islands": "MP",
    "U.S. Virgin Islands": "VI",
    "United States Minor Outlying Islands": "UM",

    # Military postal regions (often used in datasets)
    "Armed Forces Americas": "AA",
    "Armed Forces Europe": "AE",
    "Armed Forces Pacific": "AP"
}

In [300]:
for state_name in state_abbrev:
    rewards_df_sample["State"] = rewards_df_sample["State"].replace(to_replace=state_name, value = state_abbrev[state_name])

In [301]:
state_unique_values = rewards_df_sample['State'].unique()
state_unique_values = sorted(state_unique_values)
state_unique_values

['AL',
 'CA',
 'CO',
 'CT',
 'DC',
 'FL',
 'GA',
 'IL',
 'KY',
 'MA',
 'MD',
 'MN',
 'NC',
 'NJ',
 'NM',
 'NY',
 'OH',
 'PA',
 'PR',
 'SC',
 'TN',
 'TX',
 'WI']

In [302]:
state_df = pd.DataFrame(list(state_abbrev.items()) , columns=["State Name", "State"])
state_df.head()

   State Name State
0     Alabama    AL
1      Alaska    AK
2     Arizona    AZ
3    Arkansas    AR
4  California    CA

In [303]:
#Merge state code and the main df
rewards_df_sample = pd.merge(rewards_df_sample, state_df, on ='State', how="left")  #Similar to Left Join SQL

In [304]:
rewards_df_sample = rewards_df_sample.rename(columns = {"State": "State Abbreviation"})

In [305]:
rewards_df_sample.head()

,User ID,Birthdate,City,State Abbreviation,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State Name
0,1,1/31/1992,Minneapolis,GA,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00,Georgia
1,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00,Alabama
2,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00,North Carolina
3,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00,North Carolina
4,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00,Alabama

In [306]:
#Move State Name next to State Abbrev
state_name_col = rewards_df_sample.pop("State Name")
rewards_df_sample.insert(3, "State Name", state_name_col)
rewards_df_sample.head()

,User ID,Birthdate,City,State Name,State Abbreviation,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,Georgia,GA,55401,300,300,0,9/4/2020 0:15,2021-12-16 17:42:00
1,3,1/11/1990,Merida,Alabama,AL,97204,330,330,0,10/13/2020 16:20,2021-04-21 10:54:00
2,4,4/16/1990,Winston-Salem,North Carolina,NC,27106,10790,14290,3500,8/18/2020 13:21,2022-06-30 22:22:00
3,5,3/24/1994,Winston-Salem,North Carolina,NC,27109,650,650,0,8/21/2020 11:27,2020-12-30 10:57:00
4,6,10/9/1995,G,Alabama,AL,85588,7085,7395,310,8/18/2020 14:28,2022-06-08 23:55:00

In [307]:
state_unique_values = rewards_df_sample['Zip'].unique()
state_unique_values = sorted(state_unique_values)
state_unique_values

['10538',
 '11768',
 '11787',
 '13026',
 '13078',
 '13492',
 '13753',
 '14530',
 '15217',
 '19352',
 '19355',
 '19382',
 '1945',
 '2030',
 '2067',
 '20814',
 '21093',
 '22213',
 '2332',
 '2478',
 '2493',
 '2532',
 '2653',
 '27012',
 '27013',
 '27051',
 '27101',
 '27103',
 '27104',
 '27106',
 '27107',
 '27109',
 '27127',
 '27360',
 '27406',
 '27410',
 '27516',
 '27707-1634',
 '28078',
 '28079',
 '28097',
 '28115',
 '28117',
 '28173',
 '28205',
 '28209',
 '28216',
 '28262',
 '28269',
 '28277',
 '28462',
 '28655',
 '29204',
 '29466',
 '30165',
 '30273',
 '30311',
 '30338',
 '32174',
 '32223',
 '32608',
 '33157',
 '33410',
 '33596',
 '33908',
 '37204',
 '37205',
 '38112',
 '40222',
 '45174',
 '45419',
 '53217',
 '55401',
 '55439',
 '60048',
 '60085',
 '60515',
 '6067',
 '6880',
 '69694',
 '7481',
 '75205',
 '75230',
 '78620',
 '7901',
 '80123',
 '8075',
 '85588',
 '88101',
 '90266',
 '92078',
 '93312',
 '969',
 '97204']

In [308]:
rewards_df_sample["Zip"] = rewards_df_sample["Zip"].str[:5]

In [313]:
zip_code_boolean_index = rewards_df_sample["Zip"].str.len() == 5

In [314]:
zip_code_boolean_index

0       True
1       True
2       True
3       True
4       True
       ...
167     True
168     True
169     True
170     True
171    False
Name: Zip, Length: 172, dtype: bool

In [317]:
rewards_df_sample = rewards_df_sample[zip_code_boolean_index]

In [318]:
state_unique_values = rewards_df_sample['Zip'].unique()
state_unique_values = sorted(state_unique_values)
state_unique_values

['10538',
 '11768',
 '11787',
 '13026',
 '13078',
 '13492',
 '13753',
 '14530',
 '15217',
 '19352',
 '19355',
 '19382',
 '20814',
 '21093',
 '22213',
 '27012',
 '27013',
 '27051',
 '27101',
 '27103',
 '27104',
 '27106',
 '27107',
 '27109',
 '27127',
 '27360',
 '27406',
 '27410',
 '27516',
 '27707',
 '28078',
 '28079',
 '28097',
 '28115',
 '28117',
 '28173',
 '28205',
 '28209',
 '28216',
 '28262',
 '28269',
 '28277',
 '28462',
 '28655',
 '29204',
 '29466',
 '30165',
 '30273',
 '30311',
 '30338',
 '32174',
 '32223',
 '32608',
 '33157',
 '33410',
 '33596',
 '33908',
 '37204',
 '37205',
 '38112',
 '40222',
 '45174',
 '45419',
 '53217',
 '55401',
 '55439',
 '60048',
 '60085',
 '60515',
 '69694',
 '75205',
 '75230',
 '78620',
 '80123',
 '85588',
 '88101',
 '90266',
 '92078',
 '93312',
 '97204']

In [319]:
len(rewards_df_sample)

155

In [322]:
rewards_df_sample = rewards_df_sample[rewards_df_sample['City'] != "G"]
rewards_df_sample = rewards_df_sample[rewards_df_sample['City'] != "Lmao"]
len(rewards_df_sample)

153