# Random Forest

Random Forest is one of the most powerful machine learning algorithms.

Along with:

- XGBoost
- Gradient Boosting

it performs well on many types of datasets.

---

# Features

- Works for both classification and regression
- Handles non-linear data well
- Requires less feature engineering
- Usually performs well even with minimal tuning

---

# Why is it called Random Forest?

## Random

It is based on:

- random sampling of data
- random selection of features

This randomness comes from bagging.

---

## Forest

It is collection of many Decision Trees.

Since many trees are used together, it is called a:

## Forest

---

# Random Forest = Bagging + Decision Trees

Random Forest is specialization of bagging where:

- base models are Decision Trees

Each tree:

- gets different sampled dataset
- may receive different feature subsets

---

# Working

The working is similar to bagging.

## Training

1. Create multiple bootstrap datasets
2. Train one Decision Tree on each dataset
3. Each tree learns different patterns

---

## Prediction

### Classification

All trees vote.

Final prediction is majority vote.

---

### Regression

Predictions from all trees are averaged.

$$
\hat{y}
=
\frac{1}{n}
\sum_{i=1}^{n} \hat{y}_i
$$

---

# Important Idea

Single Decision Trees usually have:

- low bias
- high variance

Random Forest reduces variance by combining many trees together.

Thus it gives:

- stable predictions
- reduced overfitting

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("./Dataset/heart.csv")

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [4]:
df.shape

(303, 14)

In [5]:
X = df.drop(columns = "target")
y = df["target"]

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
print(X_train.shape)
print(X_test.shape)

(242, 13)
(61, 13)

In [10]:
rf = RandomForestClassifier()
gb = GradientBoostingClassifier()
svc = SVC()
lr = LogisticRegression()

In [11]:
gb.fit(X_train,y_train)
y_pred = gb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7704918032786885

In [14]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test,y_pred)

c:\Users\LENOVO\Desktop\Fusemachines AI Fellowship 2026\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8852459016393442

In [13]:
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
accuracy_score(y_test,y_pred)

0.7049180327868853

In [15]:
rf = RandomForestClassifier(max_samples=0.75, random_state=42)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9016393442622951

In [16]:
from sklearn.model_selection import cross_val_score
np.mean(cross_val_score(RandomForestClassifier(max_samples=0.75),X,y,cv=10,scoring='accuracy'))

np.float64(0.8348387096774192)

In [17]:
#Grid Search CV
# Number of trees in random forest
n_estimators = [20,60,100,120]

# Number of features to consider at every split
max_features = [0.2,0.6,1.0]

# Maximum number of levels in tree
max_depth = [2,8,None]

# Number of samples
max_samples = [0.5,0.75,1.0]

# 108 diff random forest train

In [18]:
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
              'max_samples':max_samples
             }
print(param_grid)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0]}

In [19]:
rf = RandomForestClassifier()

In [20]:
from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(estimator=rf, param_grid= param_grid, cv = 5 , verbose=2, n_jobs= -1)

In [21]:
rf_grid.fit(X_train,y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': [0.2, 0.6, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 60, 100, 120]},
             verbose=2)

In [22]:
rf_grid.best_params_

{'max_depth': 8, 'max_features': 0.2, 'max_samples': 0.75, 'n_estimators': 60}

In [23]:
rf_grid.best_score_

np.float64(0.8347789115646258)

In [30]:
#RandomSearchCV
# Number of trees in random forest
n_estimators = [20,60,100,120]

# Number of features to consider at every split
max_features = [0.2,0.6,1.0]

# Maximum number of levels in tree
max_depth = [2,8,None]

# Number of samples
max_samples = [0.5,0.75,1.0]

# Bootstrap samples
bootstrap = [True]

# Minimum number of samples required to split a node
min_samples_split = [2, 5]

# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2]

In [31]:
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
              'max_samples':max_samples,
              'bootstrap':bootstrap,
              'min_samples_split':min_samples_split,
              'min_samples_leaf':min_samples_leaf
             }
print(param_grid)

{'n_estimators': [20, 60, 100, 120], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0], 'bootstrap': [True], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2]}

In [32]:
from sklearn.model_selection import RandomizedSearchCV

rf_grid = RandomizedSearchCV(estimator=rf, param_distributions=param_grid, cv = 5, verbose=2, n_jobs=-1)

In [33]:
rf_grid.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'bootstrap': [True],
                                        'max_depth': [2, 8, None],
                                        'max_features': [0.2, 0.6, 1.0],
                                        'max_samples': [0.5, 0.75, 1.0],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [20, 60, 100, 120]},
                   verbose=2)

In [34]:
rf_grid.best_params_

{'n_estimators': 20,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_samples': 1.0,
 'max_features': 0.2,
 'max_depth': 2,
 'bootstrap': True}

In [35]:
rf_grid.best_score_

np.float64(0.8346088435374149)

# Bagging vs Random Forest

Although Random Forest is a specialization of Bagging, they are not exactly the same.

---

# Bagging

- Bagging is a general ensemble technique
- It can use **any algorithm** as the base estimator
  - Decision Trees
  - Logistic Regression
  - SVM, etc.

---

## Key Idea

- Each model is trained on a different bootstrap sample of data
- Final prediction is aggregated (vote/mean)

---

## Column Sampling in Bagging

Column (feature) sampling happens at the **tree/model level**

➡️ Each base model may receive a different subset of features

This means:

- one full model sees one feature subset
- another model sees a different subset

So diversity is created at model level.

---

# Random Forest

- Random Forest is a specialization of Bagging
- It uses **only Decision Trees** as base models

---

## Key Idea

- Many Decision Trees are trained
- Each tree is built on a bootstrap sample
- Extra randomness is introduced during tree building

---

## Column Sampling in Random Forest

Column sampling happens at the **node level**

➡️ At each split inside a tree, only a random subset of features is considered

This means:

- every node in a tree sees different feature choices
- even within the same tree, splitting varies

So randomness is deeper and stronger.

---

# Key Difference

| Feature | Bagging | Random Forest |
|--------|--------|--------------|
| Base model | Any model | Only Decision Trees |
| Feature sampling | Model level | Node level |
| Randomness | Moderate | Higher |
| Diversity source | Data + models | Data + nodes + features |

---

# Conclusion

- Bagging = general ensemble framework  
- Random Forest = more randomized, tree-based version of bagging

# Hyperparameters of Random Forest

---

## 1) n_estimators

Number of decision trees in the forest.  
More trees → better stability, but higher computation cost.

---

## 2) max_features

Number of features considered at each split.  
Controls randomness and reduces correlation between trees.

---

## 3) bootstrap

Whether bootstrap sampling is used when building trees.  
If True, each tree is trained on a random sample with replacement.

---

## 4) max_samples

Number (or fraction) of samples used to train each tree.  
Limits dataset size per tree to increase diversity.

---

## 5) criterion

Function used to measure split quality.  
Common options:
- Gini impurity
- Entropy (information gain)

---

## 6) max_depth

Maximum depth of each tree.  
Controls overfitting by limiting tree growth.

---

## 7) min_samples_split

Minimum number of samples required to split a node.  
Higher values prevent learning very specific patterns.

---

## 8) min_samples_leaf

Minimum number of samples required at a leaf node.  
Ensures leaves are not too small or noisy.

---

## 9) oob_score (Out-of-Bag Score)

Uses unused samples (out-of-bag samples) to evaluate model performance.  
Acts as internal validation without separate validation set.

---

## 10) n_jobs

Number of CPU cores used for training.  
- `-1` uses all available cores for faster computation.

---

## 11) class_weight

Weights assigned to classes to handle imbalance.  
Higher weight is given to minority classes to improve learning.

# OOB Score (Out-of-Bag Score)

OOB (Out-of-Bag) evaluation is a built-in validation method used in ensemble models like Random Forest.

---

## Sampling with Replacement

Sampling with replacement means:

the same data point can be selected multiple times while forming a bootstrap sample.

So some rows may appear repeatedly, while some may not appear at all.

---

## Out-of-Bag Samples

When bootstrap sampling is done:

- some rows are **not selected at all**
- these unused rows are called **out-of-bag (OOB) samples**

These samples are:

- not seen by the model during training
- naturally act like a validation set

---

## Key Insight

On average:

- about **37% of data** becomes OOB samples in Random Forest

This happens due to probability of not being selected during bootstrap sampling.

---

## OOB Score

OOB score is computed by:

- predicting each OOB sample using trees that did NOT see it
- comparing predictions with actual values

It gives an **internal estimate of model performance** without needing a separate validation set.

---

## Why OOB is Useful

- No need for train-validation split
- Efficient use of data
- Good estimate of generalization performance

---

In [36]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

In [38]:
df = pd.read_csv("Dataset/heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [40]:
X = df.drop(columns = ["target"])
y = df["target"]

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
rf = RandomForestClassifier(oob_score=True)

In [43]:
rf.fit(X_train,y_train)

RandomForestClassifier(oob_score=True)

In [45]:
rf.oob_score_

0.7851239669421488

In [46]:
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.8688524590163934

# Feature Importance

Tree-based algorithms can automatically compute feature importance, helping us understand which features contribute most to predictions.

---

## Idea

In models like Random Forest:

- each feature is used to split nodes in decision trees
- each split reduces impurity (Gini, Entropy, or SSE)
- features that reduce impurity more are considered more important

So the model learns which features are most useful for prediction directly from data.

---

## Random Forest Feature Importance

Random Forest combines importance from all decision trees in the forest.

In scikit-learn, feature importance can be accessed using:

rf.feature_importances_

---

## Interpretation

- Higher value → feature has stronger influence on prediction  
- Lower value → feature has weak or negligible influence  

All feature importance values sum to 1.

---

## How It Is Computed (Intuition)

Feature importance is calculated by:

- measuring how much a feature reduces impurity at each split  
- weighting that reduction by number of samples affected  
- summing over all trees in the forest  

So if a feature consistently improves splits across many trees, it gets a higher importance score.

---

## Key Insight

- Helps in feature selection  
- Improves interpretability of models  
- Can remove irrelevant features  
- Works only for tree-based models (Decision Trees, Random Forest, etc.)